/**
 * Sanity seed script — populates all dynamic content types with the
 * static fallback data currently hardcoded in the app.
 *
 * Usage:
 *   npx tsx scripts/seed.ts
 *
 * Note: IDs are auto-generated by Sanity. Run only once, or clear the
 * relevant document types in Sanity Studio before re-running.
 * Gallery images are excluded (they require file uploads).
 * Notes are excluded (managed directly in Sanity Studio).
 */

import { createClient } from "@sanity/client";
import * as fs from "fs";
import * as path from "path";

// ── Load .env.local manually (tsx doesn't auto-load it) ──────────────────────
const envPath = path.resolve(process.cwd(), ".env.local");
if (fs.existsSync(envPath)) {
  for (const line of fs.readFileSync(envPath, "utf8").split("\n")) {
    const match = line.match(/^([^#=]+)=(.*)$/);
    if (match)
      process.env[match[1].trim()] = match[2]
        .trim()
        .replace(/^["']|["']$/g, "");
  }
}

const client = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID!,
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET ?? "production",
  apiVersion: "2024-01-01",
  token: process.env.SANITY_API_TOKEN!,
  useCdn: false,
});

async function insert(doc: { _type: string; [key: string]: unknown }) {
  const created = await client.create(doc);
  console.log(`  ✓  ${doc._type}  ${created._id}`);
}

// ── 1. Testimonials ───────────────────────────────────────────────────────────
async function seedTestimonials() {
  console.log("\n▸ Testimonials");
  const testimonials = [
    // Testimonials page (anonymous executives)
    {
      quote:
        "TheKayodeKolade gave me the kind of counsel I didn't know I was missing — direct, independent, and completely without agenda. Within three months I had more clarity on our direction than I'd had in three years.",
      clientName: "CEO",
      clientContext: "Financial Services, West Africa",
      order: 1,
      pages: ["testimonials"],
    },
    {
      quote:
        "I came in sceptical. I left the first conversation knowing I'd be back. He sees things others don't, and he says them in a way that makes you want to act rather than defend.",
      clientName: "Managing Director",
      clientContext: "Technology, Pan-African",
      order: 2,
      pages: ["testimonials"],
    },
    {
      quote:
        "The board work he did with us changed how we function at a fundamental level. We stopped going through the motions and started doing the actual work of governance. I didn't know there was a difference until I experienced it.",
      clientName: "Board Chair",
      clientContext: "Professional Services",
      order: 3,
      pages: ["testimonials"],
    },
    {
      quote:
        "What I valued most was that he never told me what I wanted to hear. Every conversation was honest, every challenge was grounded, and every session left me better equipped than when I arrived.",
      clientName: "Executive Director",
      clientContext: "Government Advisory",
      order: 4,
      pages: ["testimonials"],
    },
    // Career clarity
    {
      quote:
        "I was stuck on what to do next to make this transition. Kayode provided clarity on the steps I needed to take — finding out what my core skills and interests were, and leveraging this to decide on a career path. Our interactions provided both the drive and direction I needed. I transitioned into project management, moved abroad for my master's, and graduated with a distinction.",
      clientName: "Ayodeji Akinola",
      clientContext: "",
      order: 5,
      pages: ["career-clarity", "home"],
    },
    {
      quote:
        "I got direction. I got practical, realistic scenarios that gave clarity. The interaction helped me make the right decision — one I am enjoying today.",
      clientName: "Adeniran Kayode",
      clientContext: "",
      order: 6,
      pages: ["career-clarity"],
    },
    {
      quote:
        "After a decade-long career, I needed guidance on how to validate my interests and shape what to pursue in the next decade. I got the clarity to invest in digital transformation rather than the default path — better positioned for the modern COO role if I get there.",
      clientName: "Temitope Awoyemi",
      clientContext: "",
      order: 7,
      pages: ["career-clarity"],
    },
    // My Story
    {
      quote:
        "You showed me how to reflect growth and career progression in spite of having the same job title. Within about four months of applying what you shared, I got two job offers — and finally left after several years of applying here and there. Recruiters still reach out to me.",
      clientName: "Victoria Ikuemonisan",
      clientContext: "",
      order: 8,
      pages: ["my-story"],
    },
    {
      quote:
        "You helped me contextualise situations, develop a comprehensive pros and cons — and even did it with me. These interactions gave me better perspective and helped me make the best decisions.",
      clientName: "Samson Richard",
      clientContext: "",
      order: 9,
      pages: ["my-story"],
    },
    // Organisational systems
    {
      quote:
        "He guided us on improving our Social Enterprise and Innovation Program — the cost of delivering quality training versus quantity trained, curriculum engagement, and how to assess the success of funded enterprises. The encounter was very valuable: we made concrete adjustments to our 2024 strategic plan, including making community trainers full-time staff.",
      clientName: "James Otai",
      clientContext: "Imagine Her (Uganda)",
      order: 10,
      pages: ["organisational-systems"],
    },
    {
      quote:
        "You are an original thinker. Your guidance was never based on fluff — very practical insights. You changed how managers and specialists think about OKRs in general.",
      clientName: "Programme Specialist",
      clientContext: "International Education Organisation",
      order: 11,
      pages: ["organisational-systems"],
    },
    // Founder architecture
    {
      quote:
        "We were trying to define what my organisation is aiming to achieve. I needed help understanding structure and how to build out ideas that are marketable. Together we created a revised vision, mission, goals, and business model for the organisation I am building.",
      clientName: "Founder",
      clientContext: "Early-stage organisation",
      order: 12,
      pages: ["founder-architecture"],
    },
    // Home page
    {
      quote:
        "Kayode is a true and impactful leader. You'd not have an encounter with him and remain the same.",
      clientName: "Senior Professional",
      clientContext: "Technology Sector",
      order: 13,
      pages: ["home"],
    },
  ];

  for (const t of testimonials) {
    await insert({
      _type: "testimonial",
      quote: t.quote,
      clientName: t.clientName,
      clientContext: t.clientContext || undefined,
      order: t.order,
      pages: t.pages,
    });
  }
}

// ── 2. Success Stories ────────────────────────────────────────────────────────
async function seedSuccessStories() {
  console.log("\n▸ Success Stories");
  const stories = [
    {
      code: "01",
      title: "The Reorientation",
      sector: "Financial Services",
      client: "Global CEO, post-acquisition integration",
      result: "Integration delivered. Leadership model rebuilt.",
      story:
        "Two organisations had merged on paper but remained cultures apart. The CEO was technically strong but had never managed transformation at this scale — and the board's patience was thinning. Over six months, we worked on two parallel tracks: the strategic framework for integration, and the CEO's own leadership model under sustained pressure. The distinction between what needed to be decided and what needed to be led wasn't obvious at the outset — but once it was, everything moved differently. The integration delivered within revised timelines. More durably, the CEO developed a personal operating model that held under pressure rather than defaulting to busyness as a substitute for direction.",
      order: 1,
    },
    {
      code: "02",
      title: "The Succession",
      sector: "Family Business",
      client: "Third-generation ownership transition",
      result:
        "Governance structure established. Succession completed without fracture.",
      story:
        "A family-owned business entering its third generational transition had never formally separated ownership from management. The second-generation leadership lacked the experience — and the mandate — to step fully into what they were about to inherit. I worked with the board, the outgoing chair, and the incoming generation over eighteen months. The work was as much relational as structural: the organisation needed governance architecture it had never required before, and the family needed a trusted third party to surface what they couldn't say to each other. What resulted was a governance structure fit for a professional organisation, a succession completed without public fracture, and a next generation in place with authority — not just titles.",
      order: 2,
    },
    {
      code: "03",
      title: "The Turnaround",
      sector: "Technology",
      client: "Interim CEO, contested board environment",
      result: "New CEO appointed. Strategy reset. Organisation stabilised.",
      story:
        "A mid-cap technology company was navigating a board crisis following the departure of its founding CEO. The interim CEO had strong operational credentials but limited experience managing a board in a contested environment — with two activist shareholders and a strategy that no longer held. I engaged directly with the interim CEO and board chair. The immediate priority was stabilisation: managing the activist dynamic while preserving management's ability to operate. The strategic review ran concurrently rather than sequentially. A new CEO was appointed through a process that managed shareholder expectations effectively. The organisation came through its most exposed period intact — and with a revised strategy that landed credibly with the market.",
      order: 3,
    },
    {
      code: "04",
      title: "The Presence",
      sector: "Media & Communications",
      client: "Senior Executive, public profile development",
      result: "Media positioning established. Keynote delivered to 2,000+.",
      story:
        "A highly capable executive was being overlooked for public-facing opportunities because she hadn't yet found a way to translate her boardroom authority into media presence. The work wasn't about polish — she had plenty of that. It was about helping her find, articulate, and hold a point of view worth having. Over four months we developed her public positioning, restructured her keynote, and prepared her for a series of media engagements she had previously declined. She delivered her first major keynote to an audience of over two thousand people. The feedback was that she was the highlight of the programme. She already knew what she believed. The work was helping her say it.",
      order: 4,
    },
  ];

  for (const s of stories) {
    await insert({
      _type: "successStory",
      code: s.code,
      title: s.title,
      sector: s.sector,
      client: s.client,
      result: s.result,
      story: s.story,
      order: s.order,
    });
  }
}

// ── 3. Marketplace Products ───────────────────────────────────────────────────
async function seedProducts() {
  console.log("\n▸ Marketplace Products");
  const products = [
    {
      title: "The Boardroom Code",
      subtitle: "What nobody tells you about executive authority",
      type: "Book",
      description:
        "A direct, practical guide to building the kind of authority that outlasts any title. Drawn from three decades of boardroom experience — the things I've told clients in private, now written down.",
      price: "$24.99",
      priceNote: "Digital + Print available",
      tag: "Bestseller",
      available: true,
      coverAccent:
        "linear-gradient(135deg, #1a1208 0%, #2d1f0a 60%, #1c1510 100%)",
      order: 1,
    },
    {
      title: "Lead Before You're Ready",
      subtitle: "On stepping into authority before you feel you deserve it",
      type: "Book",
      description:
        "The book I wish someone had handed me at the beginning of my career. A candid account of the gap between being appointed and being trusted — and how to close it faster.",
      price: "$19.99",
      priceNote: "Digital edition",
      tag: "",
      available: true,
      coverAccent:
        "linear-gradient(135deg, #0f1a0f 0%, #162010 60%, #0d140d 100%)",
      order: 2,
    },
    {
      title: "Stillness & Strategy",
      subtitle: "A leader's guide to deciding well",
      type: "Book",
      description:
        "On the discipline of slowing down before the most consequential decisions — how stillness, reflection, and a settled inner life produce better outcomes than urgency and motion.",
      price: "$21.99",
      priceNote: "Digital + Print available",
      tag: "New",
      available: true,
      coverAccent:
        "linear-gradient(135deg, #0a0f1a 0%, #101828 60%, #0c1220 100%)",
      order: 3,
    },
    {
      title: "Executive Presence Masterclass",
      subtitle: "6-week live cohort programme",
      type: "Course",
      description:
        "A structured six-week programme for senior leaders who want to develop the authority, composure, and communication clarity that define the most effective executives. Small cohort. Direct access.",
      price: "$499",
      priceNote: "Per participant · Next cohort: Sept 2026",
      tag: "Cohort",
      available: true,
      coverAccent:
        "linear-gradient(135deg, #1a1008 0%, #251a0a 60%, #1a1208 100%)",
      order: 4,
    },
  ];

  for (const p of products) {
    await insert({
      _type: "product",
      title: p.title,
      subtitle: p.subtitle,
      type: p.type,
      description: p.description,
      price: p.price,
      priceNote: p.priceNote,
      tag: p.tag || undefined,
      available: p.available,
      coverAccent: p.coverAccent,
      order: p.order,
    });
  }
}

// ── 4. Impact Organisations ───────────────────────────────────────────────────
async function seedImpactOrgs() {
  console.log(
    "\n▸ Impact Organisations (placeholder — update names in Sanity Studio)",
  );
  const orgs = [
    {
      name: "Organisation Name One",
      category: "Education & Leadership",
      role: "Board Advisory Member",
      since: "2019",
      description:
        "Supporting the development of emerging leaders across underserved communities through structured mentorship, skills training, and access to senior professional networks.",
      active: true,
      order: 1,
    },
    {
      name: "Organisation Name Two",
      category: "Governance & Policy",
      role: "Independent Advisor",
      since: "2021",
      description:
        "Providing independent counsel on governance reform and institutional strengthening for public sector organisations navigating structural transformation.",
      active: true,
      order: 2,
    },
    {
      name: "Organisation Name Three",
      category: "Youth Development",
      role: "Programme Mentor",
      since: "2020",
      description:
        "Mentoring young professionals at the early stages of their careers — helping them build clarity of direction, professional confidence, and the habits of excellent leadership.",
      active: true,
      order: 3,
    },
    {
      name: "Organisation Name Four",
      category: "Faith & Community",
      role: "Volunteer & Speaker",
      since: "2015",
      description:
        "Contributing to community building and values-based leadership development through speaking engagements, workshops, and long-term volunteer engagement.",
      active: true,
      order: 4,
    },
  ];

  for (const org of orgs) {
    await insert({
      _type: "impactOrg",
      name: org.name,
      category: org.category,
      role: org.role,
      since: org.since,
      description: org.description,
      active: org.active,
      order: org.order,
    });
  }
}

// ── 5. Site Config (singleton — uses createOrReplace with known _id) ──────────
async function seedSiteConfig() {
  console.log("\n▸ Site Config");
  await client.createOrReplace({
    _id: "siteConfig",
    _type: "siteConfig",
    calendlyUrl: "https://calendly.com/thekayodekolade",
    contactEmail: "hello@thekayodekolade.com",
    footerTagline:
      "Executive Operating System Architect · Fractional COO · Coach",
    footerBlurb:
      "Helping professionals, founders, and organisations turn clarity into operating architecture and execution momentum.",
    linkedInUrl: "https://linkedin.com",
    instagramUrl: "https://instagram.com",
    statsBar: [
      {
        _key: "stat-1",
        line: "15+ Years",
        descriptor: "Leadership, Transformation & Systems Building",
      },
      {
        _key: "stat-2",
        line: "Multi-Country",
        descriptor: "Executive Leadership Across Africa",
      },
      {
        _key: "stat-3",
        line: "Operating Models",
        descriptor: "Governance & Organisational Effectiveness",
      },
      {
        _key: "stat-4",
        line: "ICF Member",
        descriptor:
          "Brain-Based Coach · Organisational Development Practitioner",
      },
    ],
  });
  console.log("  ✓  siteConfig  siteConfig");
}

// ── 6. Hero Slides ────────────────────────────────────────────────────────────
async function seedHeroSlides() {
  console.log(
    "\n▸ Hero Slides (images must be uploaded separately in Sanity Studio)",
  );
  console.log(
    "  ℹ  Skipping — hero slides require image uploads. Create them manually in Studio.",
  );
  console.log("     Until then, the site uses the hardcoded fallback slides.");
}

// ── 7. FAQs ───────────────────────────────────────────────────────────────────
async function seedFaqs() {
  console.log("\n▸ FAQs");
  const faqs = [
    {
      question: "Am I the kind of person you work with?",
      answer:
        "If you're a professional or executive navigating a career inflection point, a founder building or restructuring a business, or a leader of a scaling organisation that needs operating systems, governance rhythms, manager development, or Fractional COO support — yes, very likely. Not every enquiry becomes an engagement; the first conversation is how we both find out whether there's a meaningful fit.",
      order: 1,
    },
    {
      question: "What happens after I reach out?",
      answer:
        "We have a direct, complimentary conversation. From there, the engagement is designed around your specific need — a structured programme, an advisory arrangement, a workshop, or a longer operating partnership.",
      order: 2,
    },
    {
      question: "Will this stay confidential?",
      answer:
        "Completely. Client relationships are never disclosed, and nothing you share is used in marketing or content without your explicit permission. Discretion is a founding principle of this practice.",
      order: 3,
    },
    {
      question: "Does location matter?",
      answer:
        "No. I'm based in the Netherlands and work with clients across Africa, Europe, and North America — engagements have spanned Nigeria, Kenya, the US, the UK, and beyond. Work runs remotely by default, and in person where proximity adds genuine value.",
      order: 4,
    },
    {
      question: "What if I'm not sure which path fits me?",
      answer:
        "That's normal — and it's literally the work. Reach out anyway and describe where you are. Helping you name the real problem is how every good engagement begins.",
      order: 5,
    },
  ];
  for (const faq of faqs) {
    await insert({
      _type: "faq",
      question: faq.question,
      answer: faq.answer,
      order: faq.order,
    });
  }
}

// ── Main ──────────────────────────────────────────────────────────────────────
async function main() {
  console.log("Sanity seed script");
  console.log(`Project: ${process.env.NEXT_PUBLIC_SANITY_PROJECT_ID}`);
  console.log(
    `Dataset: ${process.env.NEXT_PUBLIC_SANITY_DATASET ?? "production"}`,
  );

  if (
    !process.env.NEXT_PUBLIC_SANITY_PROJECT_ID ||
    !process.env.SANITY_API_TOKEN
  ) {
    console.error(
      "\n✗  Missing env vars. Check .env.local for NEXT_PUBLIC_SANITY_PROJECT_ID and SANITY_API_TOKEN.",
    );
    process.exit(1);
  }

  // await seedSiteConfig();
  await seedHeroSlides();
  // await seedFaqs();
  // await seedTestimonials();
  // await seedSuccessStories();
  // await seedProducts();
  // await seedImpactOrgs();

  console.log("\n✓  Seed complete.");
  console.log(
    "   Gallery images are excluded — upload those manually in Sanity Studio.",
  );
  console.log(
    "   Impact org names are placeholders — update them in Sanity Studio.",
  );
  console.log(
    "   Hero slides require image uploads — create them manually in Studio.",
  );
  console.log(
    "   Update LinkedIn/Instagram URLs in the Site Configuration document.",
  );
}

main().catch((err) => {
  console.error("\n✗  Seed failed:", err.message);
  process.exit(1);
});
